### ISSUE TITLE
Error: (ModuleNotFoundError: No module named 'app')

### ISSUE THREAD

**Issue by SWS-5007** [polkascan/harvester#7]
Hi,
When I run this command `python app/harvester.py --force-start`, I am getting Error like below.

> Traceback (most recent call last):
>   File "E:\Source\harvester\app\harvester.py", line 22, in <module>
>     from app import settings as app_settings, __version__, jobs
> ModuleNotFoundError: No module named 'app'

How to solve this Error?
Please help me.

**Comment by arjanz** [comment]
Add the root of the harvester dir to your PYTHONPATH
